"""empty message

Revision ID: cdf143baf610
Revises: 945f5c10a79b
Create Date: 2016-03-31 00:19:42.932824

"""

# revision identifiers, used by Alembic.
revision = 'cdf143baf610'
down_revision = '945f5c10a79b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_foreign_key('fk_user_school', 'users', 'school', ['school_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_school', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_column(u'users', 'school_id')
    op.drop_table('school')
    ### end Alembic commands ###
