"""empty message

Revision ID: eddd01fd602a
Revises: None
Create Date: 2016-03-29 11:25:04.820755

"""

# revision identifiers, used by Alembic.
revision = 'eddd01fd602a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
